language: c
addons:
  apt:
    packages:
    - libasound2:i386
    - lib32z1
    - lib32bz2-1.0
    - libssl1.0.0:i386
    - libfreetype6:i386
script:
- if [[ ${TRAVIS_BRANCH} == "master" ]]; then make deploy; fi
env:
  global:
    secure: WJEnSkogD5sednB4drLW1EIyaezWJhHAqxYXeyvw0iYWwT0t0m/BVB4y87vaR5oCgf81t5vS9gDMyhbTQSuuQw2JBE5asY2Rs/ucNo2Q7l0JF+PZ+A2j3eOZCLVRZ66OT4L4fWvg5H0MWmXz7sYPS0vPLPAb1ApxV4hZeN7oMyjrTxSr0U1nPbV9K1OrtFtu03hB2G/JrGRNp5QyYJRDX8ZZbVvRIEfdlK/Y63nyAbPKBM27pUQVesemfXg4Uomnx571DfNBTo5a4D/tmYYD3P6tB0P89WDyE9FmBYDbZjz+WzQ0RewTYZUPHISwQCH2y98Yf/k6LMRupkAfT2cq6cXDVpoMyNvgjvOcS+v52AnIIJ/nPErolTpM13RD4OpGlpOYMZDOMB+CkVfdWjeGXeCY+akmY+r1RNltUo9KgLT2KGLz5cLQ5wcHczEQUVDA8hpm0sbpeTxRDDRx3rTqsdl9ZD1xvsbrbdNYWAmNxY5OJ3/Fahcx6vcPT2+tEVFvTL9UY+W3GBUw0oQ3d9pIpoWcOc8faVO/XFJt5YZB6vVFN0784mNp7N0NhgQPk2AlbD8NMh9mg5KcLzXcFZVEevRgqjW9UyP3pC1Tp7ssGDAIKROyqe791Yh3GoQx7gH9ADXId4DjDM1DrdpNYugZmVUKu5PL+BKL/mztMLQm1vg=
